name: Publisoft deplyment

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  REGION: us-central1

jobs:

    setup:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Authenticate with Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1

        - name: Set Active Account
          run: |
            gcloud auth list
            gcloud config set account $(gcloud auth list --filter=status:ACTIVE --format="value(account)")

        - name: Set GCP Project
          run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


    deploy-api:
      needs: [setup]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Create .env File
          run: |
            echo "${{ secrets.PROD_ENV_API }}" > ./api/.env

        - name: Deploy API to Cloud Run
          run: |
            gcloud builds submit ./api --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/api --project ${{ secrets.GCP_PROJECT_ID }}
            gcloud run deploy api \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api \
              --platform managed \
              --region $REGION \
              --allow-unauthenticated

    deploy-client:
      needs: [setup]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Create .env File
          run: |
            echo "${{ secrets.PROD_ENV_CLIENT }}" > ./client/.env

        - name: Deploy Client to Cloud Run
          run: |
            gcloud builds submit ./client --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/client --project ${{ secrets.GCP_PROJECT_ID }}
            gcloud run deploy client \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/client \
              --platform managed \
              --region $REGION \
              --allow-unauthenticated

    deploy-nginx:
      needs: [deploy-api, deploy-client]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          
        - name: Update Nginx config with correct URLs
          run: |
            sed -i "s|https://frontend-url.a.run.app|https://$(gcloud run services describe client --platform managed --region $REGION --format='value(status.url)')|g" nginx/default.conf
            sed -i "s|https://backend-url.a.run.app|https://$(gcloud run services describe api --platform managed --region $REGION --format='value(status.url)')|g" nginx/default.conf
        
        - name: Deploy Nginx Gateway
          run: |
            gcloud builds submit ./nginx --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-gateway
            gcloud run deploy my-gateway \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-gateway \
              --platform managed \
              --region $REGION \
              --allow-unauthenticated
